panjf2000/ants

- ants_test.go
- pool.go
- pool_func.go
- worker.go
- worker_func.go
fix #3 
* 链表实际测过， 性能相差无几， 但内存占用高了几倍
* 初始化`Pool`和`PoolFunc`是给定了个默认的worker capacity
* 优化了下其他代码
> pre-allocate the capacity of the worker list

- ants_benchmark_test.go
Benchmark results with Param=0, as time.Sleep is not stable on Windows
Also Go 1.11 has bunch of improvements:
```
goos: windows
goarch: amd64
pkg: github.com/panjf2000/ants
BenchmarkGoroutineWithFunc-8           1        3530220300 ns/op          207472 B/op        506 allocs/op
BenchmarkSemaphoreWithFunc-8           1        4391916400 ns/op           20944 B/op         57 allocs/op
BenchmarkAntsPoolWithFunc-8            1        5496395400 ns/op          164240 B/op       2059 allocs/op
BenchmarkGoroutine-8                   1        3327413400 ns/op            1552 B/op          5 allocs/op
BenchmarkSemaphore-8                   1        4499816000 ns/op            1264 B/op          5 allocs/op
BenchmarkAntsPool-8                    1        5456432100 ns/op           49208 B/op …
```
> Fixes to benchmarks and added semaphore comparison

- pool.go
- pool_func.go
// NewTicker returns a new Ticker containing a channel that will send the
// time with a period specified by the duration argument.
// It adjusts the intervals or drops ticks to make up for slow receivers.
// The duration d must be greater than zero; if not, NewTicker will panic.
// Stop the ticker to release associated resources.
func NewTicker(d Duration) *Ticker {
……
}
> Possible memory leak because of Ticker

- ants.go
Added a newline between group comment and exported variable line 😄
> goreport: lint warning on code comment structure

- ants_test.go
- coverage.txt
- pool.go
- pool_func.go
- worker.go
- worker_func.go
Hi, I am using it on my online server which almost need 5 million goroutines on each go service.
I'm divided into 10 small pools, because a pool of five million will slow down the speed associated with the slice.
I made some small optimizations, I hope this is useful.
optimize memory allocation, change the default pool param and add the log of panic stack.
btw, the default value DEFAULT_CLEAN_INTERVAL_TIME, one second is too short-lived. when the pool size is too large , Performance will drop .
> optimize memory allocation, change the default pool param and add the log of panic stack.

- worker.go
- worker_func.go
Signed-off-by: Cholerae Hu <choleraehyq@gmail.com>
---
title: ''
labels: ''
assignees: ''
---
> Invoke decRunning() when revertWorker() returns false

- pool.go
err!=nil时未释放锁，使用defer p.lock.Unlock()修复
---
title: ''
labels: ''
assignees: ''
---
> Fix a bug that doesn't release lock

- pool.go
- worker_loop_queue.go
- worker_stack.go
---
title: 'avoid memory leaky'
labels: 'gc'
assignees: ''
---
bug fix
我认为在对stack,loop queue在出栈或出队需要对不使用的切片元素进行置为nil操作,因为是指针,不应该留在未使用的切片位置,在突发任务需要goroutine时,会分配大量的goWorker并进入工作,但是当没有突发任务时,这些都在空闲队列或队列中是没有回收的,但是当超过存活时间,进行回收时,还是有底层的数据持有(未置为nil),个人认为会占有大量的内存,这部份应该真正的交还给sync.Pool.
另外,假设在sync.Pool和切片底层数组同时持有同一个对象,不知道go的gc是什么行为?
> Avoid memory leak

- ants_test.go
On some machines this unit would fail due to a timing issue.  Since the Invoke in the loop was using nil as the param, it would (depending on timing) lead to the workers finishing the  (w *goWorkerWithFunc) run() in the range loop over w.args as args would == nil and return. 
If an explicit time.Sleep(1 * time.Second) is added before the "	assert.EqualError(t, p.Invoke(nil), ErrPoolOverload.Error()," it is easily reproducible.
---
title: ''
labels: ''
assignees: ''
---
bug-fix
stated above
n/a
n/a
> Timing issue in the TestNonblockingSubmitWithFunc

- README.md
Hello! I never got the chance to mention it before, but thank you for linking one of my articles in your repository :) 
No
I'm working on migrating my domain from `twinnation.org` to `twin.sh`, thus I'm preemptively updating the link to prevent it from becoming dead at some point
N/A
N/A
> Update the link of one of the relevant articles

- worker_loop_queue.go
- worker_loop_queue_test.go
---
about:  Add binarysearch method to loop_queue to get expired workers, just like worker_stack.
title: ''
labels: ''
assignees: 'bright2227'
---
optimizations 
I found that loop_queue had an intention to use binarysearch method, just like worker_stack. But it's removed before being merged into the master branch due to some bugs.  I mapped true positions to imaginary positions before using binarysearch method and also add some tests to make sure it works.
https://github.com/panjf2000/ants/pull/53#pullrequestreview-299506068
No need.
> Add binarysearch of loop queue

- ants_test.go
- pool.go
- pool_func.go
…capacity
---
title: 'Instantly scale up capacity when using Tune(size int) to enlarge the capacity'
labels: 'enhancement'
assignees: ''
---
When using Tune(size int) to enlarge the capacity, create a worker immediately to perform blocking tasks.
close #205
> Awake the blocking callers when Tune(size int) is invoked to expand the pool

- .github/workflows/test.yml
- ants.go
- ants_benchmark_test.go
- ants_test.go
- go.mod
- go.sum
- pool.go
- pool_func.go
---
title: ''
labels: ''
assignees: ''
---
> opt: cache current time for workders and update it periodically

- pool.go
- pool_func.go
---
about: Fixes a bug
title: 'fix ticktock memory leaks'
labels: ''
assignees: ''
---
bugfix
The fix enables ticktock goroutine to stop it's execution.
https://github.com/panjf2000/ants/issues/263
-
> fix: exit ticktock goroutine when pool is closed

- .github/workflows/test.yml
- ants.go
---
title: ''
labels: ''
assignees: ''
---
bug-fixs
暂时先在 ants.go 里自定义了一个 log.Lmsgprefix 的值 64 。
[[Bug]: go.mod 中的go version(1.13)和ants.go存在不匹配 #274](https://github.com/panjf2000/ants/issues/274)
ants.go
> bug: fix the missing log.Lmsgprefix in go1.13

- ants.go
- ants_test.go
---
name: Unblock goPurge and goTicktock in defaultAntsPool
about: ants.Release() calls defaultAntsPool.Release() which leaves goPurge and goTicktock still running in the background. ants.Release() should close the context for goPurge and goTicktock. This can be accomplished by calling defaultAntsPool.ReleaseTimeout(<large number>). 
title: 'Unblock goPurge and goTicktock in defaultAntsPool'
labels: ''
assignees: ''
---
Bug-fix.
goPurge and goTicktock are left on the stack because there is no way to close those methods started by the defaultAntsPool. This PR should add a fix for that.   
https://github.com/panjf2000/ants/issues/244
> feat: add a new API `ReleaseTimeout` for the default pool

- pool.go
- pool_func.go
…rom Release method
---
name: Refactor Release Methods
about: Call cleanup functions when Release() is called. 
title: ''
labels: ''
assignees: ''
---
Bug fix.
By moving stopTicktock and stopPurge into Release() methods from ReleaseTimeout(), these functions will be stopped when Release() is called. 
https://github.com/panjf2000/ants/issues/244
> opt: fix the potential goroutine leak after calling `Release()`

- pool.go
- pool_func.go
---
title: 'make func of retrieveWorker() more readable.'
labels: ''
assignees: ''
---
refactor
I noticed that when I call `retrieveWorker()`, it processes two repetitive functions: `detach()` and `capacity == -1 || capacity > p.Running()` in the `else` block.
Thus, I move the `retry` label to the first instance of the `detach()` function and made a little change of if-else block.
It didn't affect the logic, but it is more readable.
`before`
```go
// retrieveWorker returns an available worker to run the tasks.
func (p *Pool) retrieveWorker() (w worker) {
spawnWorker := func() {
w = p.workerCache.Get().(*goWorker)
w.run()
}
p.lock.Lock()
w = p.workers.detach()
if w != nil { // first try to fetch the worker from the queue
p.lock.Unlock() …
```
> refactor: refine the code in `retrieveWorker` to make it more readable

- multipool.go
- multipool_func.go
Yes, for small optimization of multi pools. 
If lbs is invalid then we should immediately return from `NewMultiPool` func instead of creating pool arrays and then check for lbs validation
NA
NA
> bug: return error before creating multi pools if lbs is invalid to avoid leaks

- .github/workflows/test.yml
Updates:
There is an [uncanny issue](https://github.com/panjf2000/ants/actions/runs/9546726268/job/26310385582) arising when downloading go modules on macOS 13 for Go1.13. So we use macOS 12 for now.
---
Starting macOS 14 GitHub Actions runners are arm-based but Go didn't support arm64 until 1.16, which will result in [some CI failure](https://github.com/panjf2000/ants/actions/runs/9545685155/job/26306999794) after the `macos-latest` had been migrated from macOS 12 to 14. Thus, we must replace the macOS 14 runner with the macOS 13 runner for Go 1.13.
Check out https://github.com/actions/runner-images/issues/9741 for more details.
> ci: replace macos-latest with macos-12 for go1.13

- pool.go
- pool_func.go
- worker.go
- worker_func.go
Also, this PR utilizes embedding structs to eliminate duplicate fields of `Pool` and `PoolWithFunc`.
> opt: make ReleaseTimeout() more efficient in waiting workers to exit
